# Generated by Django 5.2.11 on 2026-02-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('nationality', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('borrowed', 'borrowed'), ('lost', 'lost')], default='available', max_length=20)),
                ('barcode', models.CharField(max_length=128, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='books.book')),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_borrowed_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_copies',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('fine', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='books.bookcopy')),
                ('borrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_book_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_title_7a737c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_author__4f60e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['barcode'], name='book_copies_barcode_667200_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['borrowed_by'], name='book_copies_borrowe_44396a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['book', 'status'], name='book_copies_book_id_0fba91_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('borrowed_by__isnull', True), ('status', 'available')), models.Q(('borrowed_by__isnull', False), ('status', 'borrowed')), ('status', 'lost'), _connector='OR'), name='copy_status_borrower_constraint'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['book_copy'], name='book_transa_book_co_e6e520_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['borrowed_by'], name='book_transa_borrowe_f6a291_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book_copy',), name='one_active_transaction_per_copy'),
        ),
    ]
