# Generated by Django 5.2.11 on 2026-02-10 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_borrow_days_without_fine', models.IntegerField(default=14, help_text='Number of days before fines start accruing')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=1.0, help_text='Fine amount per day after due date', max_digits=5)),
                ('max_books_per_member', models.IntegerField(default=3, help_text='Maximum number of books a member can borrow simultaneously')),
            ],
            options={
                'verbose_name': 'Library Configuration',
                'verbose_name_plural': 'Library Configuration',
                'db_table': 'library_config',
            },
        ),
        migrations.RemoveConstraint(
            model_name='bookcopy',
            name='copy_status_borrower_constraint',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fine_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fine_collected'], name='book_transa_fine_co_19b4f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('borrowed_by__isnull', True), ('status', 'available')), models.Q(('borrowed_by__isnull', False), ('status', 'borrowed')), ('status', 'lost'), models.Q(('borrowed_by__isnull', True), ('status', 'maintenance')), _connector='OR'), name='copy_status_borrower_constraint'),
        ),
    ]
